# Generated by Django 3.0 on 2025-02-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.CharField(max_length=300),
        ),
    ]
