# Generated by Django 3.0 on 2025-02-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250218_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='USER',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='COMPANY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JOB',
            field=models.CharField(max_length=100),
        ),
    ]
