# Generated by Django 3.0 on 2025-03-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250218_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='CV',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
