# Generated by Django 3.0 on 2025-03-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250319_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='certificate',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='qualification',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
