# Generated by Django 3.0 on 2025-03-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20250319_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='workplace',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
