# Generated by Django 3.0 on 2025-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_guide_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='companydetails',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='eligibility',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guide',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
    ]
