# Generated by Django 3.0 on 2025-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20250319_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='qualification',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='guide',
            name='workplace',
            field=models.CharField(max_length=500),
        ),
    ]
