# Generated by Django 3.0 on 2025-03-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20250319_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='place',
            field=models.CharField(max_length=200),
        ),
    ]
