# Generated by Django 3.0 on 2025-03-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20250319_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='certificate',
            field=models.CharField(max_length=500),
        ),
    ]
