# Generated by Django 3.0 on 2025-03-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20250319_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='liscenceno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='district',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='guide',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
